name: Nightly selenium test with Maven

on:
  schedule:
    - cron: '05 22 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Desteklenen Java dağıtımları
          java-version: '11'

      - name: Build and Test with Maven
        run: mvn -B clean test
